title: The Game Awards for Games Who Can't Afford the Game Awards
email: mail@tgagwcaga.com
description: >-
  We love the Game Awards but we're struggling to pay rent. Showcasing and celebrating the amazing indies that also have no money for events!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://TheGAGWCAGA.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: images/logo.jpg

sass:
  sass_dir:           _sass
  style:              compressed

collections:
  games:
    output: true
    layout: default

excerpt_separator: <!--more-->

exclude:
  - '*.rb'
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
